name: Schedule Test 

on:
  schedule:
    - cron: '44 8 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Time
        run: |
          echo "GitHub Schedule Works!"
          date
