name: Schedule Test

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Schedule
        run: |
          echo "Schedule is working"
          date
